### ISSUE TITLE
bug: 不断弹出“双击删除某门课”

### ISSUE THREAD

**Issue by vanyoudoor** [Fros1er/SUSTechTISHelper#1]
![image](https://user-images.githubusercontent.com/90190491/212378457-47354faa-323c-49d3-8bd4-31a948660e9a.png)

**Comment by Fros1er** [comment]
描述一下复现方法？

**Comment by vanyoudoor** [comment]
复制js代码到油猴，用edge浏览器进入南方科技大学教务系统，点击我要选课。就这样了
