### ISSUE TITLE
字体和背景颜色问题

### ISSUE THREAD

**Issue by MuuuShin** [Fros1er/SUSTechTISHelper#2]
如图 貌似会出现全是白色的情况

![image](https://user-images.githubusercontent.com/97760035/216785198-6eaabea5-aecd-4675-a82d-93d76ce480b1.png)

**Comment by Fros1er** [comment]
我去改改隔壁timetable...

**Comment by Fros1er** [comment]
修了
jsdelvir需要时间同步，没测。如果还有问题reopen一下(
